                NUMPY ARRAYS 

In [1]:
import numpy as np

In [2]:
myList = [1,2,3]

In [6]:
type(myList)

list

In [7]:
np.array(myList)

array([1, 2, 3])

In [8]:
myList

[1, 2, 3]

this will cast myList into a 2D Array ~ np.array()

In [11]:
myArr = np.array(myList)

In [14]:
myArr

array([1, 2, 3])

In [13]:
type(myArr)

numpy.ndarray

In [15]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [22]:
my_matrix
#type(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [23]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.arange(010)

SyntaxError: invalid syntax (3731655584.py, line 1)